### PR TITLE
script fixes

### PR DESCRIPTION
**Pull request by ahgittin**
i think this is wanted -- haven't tested yet tho

good spot to go through branches!

### CODE REVIEW

**Comment by ahgittin** [comment]
why not use a whitelist for `brooklyn-server` ?

**Comment by ahgittin** [comment]
should we drop the `M` and `rc` branches?  that would speed things up considerably, and i don't think we need them.  we will still have the `incubator` repo.

**Comment by ahgittin** [comment]
and drop `0.4` and `0.5` in favor of `0.x.0...`?

**Comment by ahgittin** [comment]
BTW (notes to self as much as to you) - the pre-processing can use

    git log --format='%H' --name-status --follow -- <file>

start with a set of all the paths.  loop through that set, running this command, collecting all the files mentioned which are listed (and weren't in the set) and add them to the set.  when we reach the end of the set i think we've got all the relevant files.

**Comment by ahgittin** [comment]
here's a script which shows all previous names of any contents of `$DIRS` and any previous names of them

takes about 20m on my mac for brooklyn `api/ core/`, seems to work fine but may need some tweaking.  if/when i get the chance i'll open a new PR with bigger whitelists, but can't do it right now.

```
# inputs

export DIRS=bar/
export REPO=sample/

# output

export ORIG_DIR=`pwd`
export OUTPUT=${ORIG_DIR}/TODO-all


# working

# file/paths we have left to look at, built up for the next cycle on one cycle,
# starting with the DIRS
export TODO_REMAINING=${ORIG_DIR}/TODO-remaining

# file/paths encountered on one cycle
export TODO_HERE=${ORIG_DIR}/TODO-here


rm $OUTPUT
for x in $DIRS ; do echo $x >> $OUTPUT ; done
cp $OUTPUT $TODO_REMAINING

pushd $REPO > /dev/null

echo scanning $REPO for all files

while [ -s $TODO_REMAINING ] ; do

  echo current scan has `wc $TODO_REMAINING | awk '{print $1}'` paths including `head -1 $TODO_REMAINING`
  rm -f $TODO_HERE
  touch $TODO_HERE

  for x in `cat $TODO_REMAINING` ; do
    git log --format='%H' --name-status --follow -- $x | awk '{if ($2) print $2; if ($3) print $3;}' | sort | uniq | cat $TODO_HERE - > ${TODO_HERE}2
    mv ${TODO_HERE}2 ${TODO_HERE}
  done
  cat ${TODO_HERE} | sort | uniq > ${TODO_HERE}2
  mv ${TODO_HERE}2 ${TODO_HERE}

  diff --new-line-format="" --unchanged-line-format="" ${TODO_HERE} $OUTPUT > ${TODO_HERE}_new
  cat $OUTPUT ${TODO_HERE}_new > ${OUTPUT}2
  mv ${OUTPUT}2 ${OUTPUT}
  mv ${TODO_HERE}_new $TODO_REMAINING

done

popd > /dev/null

rm ${TODO_REMAINING}
rm ${TODO_HERE}

echo completed scan of $REPO, history has `wc ${OUTPUT} | awk '{print $1}'` files
```

**Comment by ahgittin** [comment]
another comment, i think we should restructure *in* `incubator-brooklyn`, and plan to check that in as the last commit (or last but one, if we , add a comment about it moving), and the new projects taking that as the last commit

this will make it much easier to track history into incubator, show we need to, and to do merges/rebases for pr's across the two projects

i think we discussed this on email but i didn't see it in the script (didn't look to closely yet though)

also we need to add a step which removes big files, might as well do this once on a local copy and then base the new repos on this local copy, as per svet's email

**Comment by rdowner** [comment]
Thanks for the fixes @ahgittin - merging.

To answer a few questions...

> why not use a whitelist for `brooklyn-server` ?

Basically as an insurance policy - `brooklyn-server` is everything that the others are not, so we can be sure that every historical folder will be in at least one of the new repos. If a historical folder name is missed out of one of the repo's whitelists, we know that it will still be in `brooklyn-server`.

> should we drop the `M` and `rc` branches? that would speed things up considerably, and i don't think we need them. we will still have the `incubator` repo.

Actually it's not much of a speed penalty - going from master-only to master-with-all-release branches changed the number of commits from around 12,600 to 13,000 - a pretty marginal increase.

> and drop `0.4` and `0.5` in favor of `0.x.0`...?

Do you mean rename the branches instead of drop? If so that's an easy thing to do.

> another comment, i think we should restructure *in* `incubator-brooklyn`

When I tried this, when you look at the history in the GitHub "commits" page, it stopped on the rename. So the new repository looked at first glance as if it had no history. It was still all there of course, but only if you drilled down into it.

> also we need to add a step which removes big files

The script has a prototype for doing this, commented out at the top (commented out because it involved another 15-minutes pass over the repo, and I was more interested in debugging the split section).

**Comment by ahgittin** [comment]
> > why not use a whitelist for brooklyn-server ?

> Basically as an insurance policy - brooklyn-server is everything that the others are not, so we can be sure that every historical folder will be in at least one of the new repos. If a historical folder name is missed out of one of the repo's whitelists, we know that it will still be in brooklyn-server.

that makes sense esp wrt historical items.  however i'm not sure we care about that history -- we have the provenance of all the current code without this which is the main thing.

-0

**Pull request merged**
