### PR TITLE
Exploded scripts

### PR DESCRIPTION
**Pull request by ahgittin**
bunch of changes to make everything work nicely, including initial sample generated files (not quite right yet, but next run should fix it)

### CODE REVIEW

**Comment by ahgittin** [comment]
this is working well.  takes about 2h total.  content looks good.

the poms/changes from @johnmccabe will apply after step 1 (rearrange) -- or before if appropriate -- and then we're all set to do 2 through 4 and cut across methinks!

@rdowner if you want me to squash some of these for easier review let me know.  the logic might be interesting if you're doing a deep analysis but simplest probably to just look at the diff.  or happy to talk you through it, ping me on irc/skype.  (hope you feel better btw!)

**Comment by johnmccabe** [comment]
I'm still working through a repo here - https://github.com/johnmccabe/PRESPLIT-incubator-brooklyn/tree/reorg - moving tests from brooklyn-server at the moment.

@ahgittin / @rdowner I'm just created a dumb pom.xml for libraries based on a combination of the root and parent poms from the existing repo - is this what you were thinking for the root of the new projects? (redundant deps etc will be purged at some point)

**Comment by johnmccabe** [comment]
@rdowner can this be merged

**Comment by ahgittin** [comment]
Repo out of date.  Closing.  The actual code used for the reorg is what is contained in https://github.com/ahgittin/brooklyn-repo-split master branch.  This PR is a subset of that.

**Pull request closed without merging**
